package com.example.myapplication.util

class BazaarItemName {
    companion object {
        fun parseItemName(item: String): String {
            return when (item.lowercase()) {
                "可可豆", "咖啡豆" -> "INK_SACK:3"
                "棕蘑菇", "白蘑菇", "棕色蘑菇", "白色蘑菇" -> "BROWN_MUSHROOM"
                "青金石" -> "INK_SACK:4"
                "黑糖", "万圣节碎片" -> "SPOOKY_SHARD"
                "狼蛛网" -> "TARANTULA_WEB"
                "胡萝卜", "萝卜" -> "CARROT_ITEM"
                "附魔土豆", "附魔马铃薯" -> "ENCHANTED_POTATO"
                "附魔粘液球", "附魔史莱姆球" -> "ENCHANTED_SLIME_BALL"
                "附魔金萝卜", "附魔金胡萝卜" -> "ENCHANTED_GOLDEN_CARROT"
                "附魔红蘑菇", "附魔红色蘑菇" -> "ENCHANTED_RED_MUSHROOM"
                "附魔兔子皮" -> "ENCHANTED_RABBIT_HIDE"
                "附魔白桦木" -> "ENCHANTED_BIRCH_LOG"
                "附魔火药" -> "ENCHANTED_GUNPOWDER"
                "附魔西瓜", "附魔西瓜片" -> "ENCHANTED_MELON"
                "附魔糖" -> "ENCHANTED_SUGAR"
                "仙人掌" -> "CACTUS"
                "附魔烈焰棒" -> "ENCHANTED_BLAZE_ROD"
                "附魔蛋糕" -> "ENCHANTED_CAKE"
                "南瓜" -> "PUMPKIN"
                "附魔棕色蘑菇", "附魔白色蘑菇", "附魔棕蘑菇", "附魔白蘑菇" -> "ENCHANTED_BROWN_MUSHROOM"
                "护士鲨牙", "护士鲨牙齿" -> "NURSE_SHARK_TOOTH"
                "小麦" -> "WHEAT"
                "附魔生鲑鱼" -> "ENCHANTED_RAW_SALMON"
                "附魔金西瓜", "附魔闪烁的西瓜" -> "ENCHANTED_GLISTERING_MELON"
                "海晶碎片" -> "PRISMARINE_SHARD"
                "守卫者碎片" -> "PROTECTOR_FRAGMENT"
                "附魔绿宝石" -> "ENCHANTED_EMERALD"
                "附魔蜘蛛眼" -> "ENCHANTED_SPIDER_EYE"
                "红蘑菇", "红色蘑菇" -> "RED_MUSHROOM"
                "羊肉", "羊排" -> "MUTTON"
                "附魔西瓜块" -> "ENCHANTED_MELON_BLOCK"
                "鲨鱼鱼鳞", "鲨鱼鳞" -> "SHARK_FIN"
                "钻石" -> "DIAMOND"
                "wise龙碎片" -> "WISE_FRAGMENT"
                "原石", "圆石", "石头" -> "COBBLESTONE"
                "蜘蛛眼" -> "SPIDER_EYE"
                "鱼", "生鱼" -> "RAW_FISH"
                "附魔河豚" -> "ENCHANTED_PUFFERFISH"
                "土豆", "马铃薯" -> "POTATO_ITEM"
                "附魔棕色蘑菇块", "附魔白色蘑菇块", "附魔棕蘑菇块", "附魔白蘑菇块" -> "ENCHANTED_HUGE_MUSHROOM_1"
                "附魔原石", "附魔圆石" -> "ENCHANTED_COBBLESTONE"
                "附魔红色蘑菇块", "附魔红蘑菇块" -> "HUGE_MUSHROOM_2"
                "猪肉", "猪排" -> "PORK"
                "海晶沙砾" -> "PRISMARINE_CRYSTALS"
                "冰" -> "ICE"
                "虎鲨牙", "虎鲨牙齿" -> "TIGER_SHARK_TOOTH"
                "棕蘑菇块", "白蘑菇块", "棕色蘑菇块", "白色蘑菇块" -> "HUGE_MUSHROOM_1"
                "红蘑菇块", "红色蘑菇块" -> "HUGE_MUSHROOM_2"
                "冰鱼饵", "冰诱饵" -> "ICE_BAIT"
                "附魔雪块" -> "ENCHANTED_SNOW_BLOCK"
                "线" -> "STRING"
                "金牙", "金狼牙", "附魔金狼牙" -> "GOLDEN_TOOTH"
                "强化催化剂", "强力催化剂" -> "HYPER_CATALYST"
                "兔子脚" -> "RABBIT_FOOT"
                "红石" -> "REDSTONE"
                "南瓜肚子" -> "PUMPKIN_GUTS"
                "附魔仙人掌绿" -> "ENCHANTED_CACTUS_GREEN"
                "曲奇" -> "BOOSTER_COOKIE"
                "附魔胡萝卜钓竿", "附魔萝卜钓竿" -> "ENCHANTED_CARROT_ON_A_STICK"
                "附魔青金石块" -> "ENCHANTED_LAPIS_LAZULI_BLOCK"
                "附魔曲奇" -> "ENCHANTED_COOKIE"
                "附魔末地石" -> "ENCHANTED_ENDSTONE"
                "附魔沙子" -> "ENCHANTED_SAND"
                "附魔线" -> "ENCHANTED_STRING"
                "strong龙碎片" -> "STRONG_FRAGMENT"
                "粘液球", "史莱姆球" -> "SLIME_BALL"
                "雪球" -> "SNOW_BALL"
                "附魔金合欢木" -> "ENCHANTED_ACACIA_LOG"
                "holy龙碎片" -> "HOLY_FRAGMENT"
                "附魔鸡蛋", "附魔蛋" -> "ENCHANTED_EGG"
                "沙子" -> "SAND"
                "灵魂碎片" -> "SOUL_FRAGMENT"
                "生鸡肉" -> "RAW_CHICKEN"
                "狮鹫爪子", "狮鹫爪" -> "ANCIENT_CLAW"
                "附魔青金石" -> "ENCHANTED_LAPIS_LAZULI"
                "附魔恶魂之泪" -> "ENCHANTED_GHAST_TEAR"
                "附魔可可豆" -> "ENCHANTED_COCOA"
                "胡萝卜诱饵" -> "CARROT_BAIT"
                "种子" -> "SEEDS"
                "附魔皮革" -> "ENCHANTED_LEATHER"
                "附魔海绵" -> "ENCHANTED_SPONGE"
                "附魔鲨鱼鳞", "附魔鲨鱼鱼鳞" -> "ENCHANTED_SHARK_FIN"
                "甘草块" -> "HAY_BLOCK"
                "墨囊" -> "INK_SACK"
                "隧石" -> "FLINT"
                "狼牙" -> "WOLF_TOOTH"
                "附魔腐肉" -> "ENCHANTED_ROTTEN_FLESH"
                "附魔云杉木" -> "ENCHANTED_SPRUCE_LOG"
                "附魔熟猪肉", "附魔熟猪排" -> "ENCHANTED_GRILLED_PORK"
                "附魔地狱疣" -> "ENCHANTED_NETHER_STALK"
                "突变地狱疣", "变异地狱疣", "突变型地狱疣", "变异型地狱疣" -> "MUTANT_NETHER_STALK"
                "附魔红石块" -> "ENCHANTED_REDSTONE_BLOCK"
                "附魔石英块" -> "ENCHANTED_QUARTZ_BLOCK"
                "附魔狮鹫爪" -> "ENCHANTED_ANCIENT_CLAW"
                "绿糖" -> "GREEN_CANDY"
                "附魔红石" -> "ENCHANTED_REDSTONE"
                "附魔红石灯" -> "ENCHANTED_REDSTONE_LAMP"
                "大白鲨牙齿", "大白鲨牙" -> "GREAT_WHITE_SHARK_TOOTH"
                "沙砾" -> "GRAVEL"
                "西瓜" -> "MELON"
                "附魔岩浆桶" -> "ENCHANTED_LAVA_BUCKET"
                "附魔浮冰" -> "ENCHANTED_PACKED_ICE"
                "河豚" -> "RAW_FISH:3"
                "附魔海晶碎片" -> "ENCHANTED_PRISMARINE_SHARD"
                "rec3000", "3000", "r3000" -> "RECOMBOBULATOR_3000"
                "附魔铁块" -> "ENCHANTED_IRON_BLOCK"
                "附魔胡萝卜棍", "附魔萝卜棍" -> "ENCHANTED_CARROT_STICK"
                "骨头" -> "BONE"
                "小丑鱼" -> "RAW_FISH:2"
                "生鲑鱼", "鲑鱼" -> "RAW_FISH:2"
                "亡魂腐肉" -> "REVENANT_FLESH"
                "附魔生猪排", "附魔生猪肉", "附魔猪肉", "附魔猪排" -> "ENCHANTED_PORK"
                "附魔萤石" -> "ENCHANTED_GLOWSTONE"
                "羽毛" -> "FEATHER"
                "鲸鱼鱼饵", "鲸鱼饵", "鲸鱼诱饵" -> "WHALE_BAIT"
                "地狱岩" -> "NETHERRACK"
                "海绵" -> "SPONGE"
                "烈焰棒" -> "BLAZE_ROD"
                "附魔深色橡木" -> "ENCHANTED_DARK_OAK_LOG"
                "young龙碎片" -> "YOUNG_FRAGMENT"
                "附魔小丑鱼" -> "ENCHANTED_CLOWNFISH"
                "精致矿物" -> "REFINED_MINERAL"
                "附魔金锭" -> "ENCHANTED_GOLD"
                "附魔生鸡肉" -> "ENCHANTED_RAW_CHICKEN"
                "附魔睡莲", "附魔荷叶" -> "ENCHANTED_WATER_LILY"
                "蓝鲨牙", "蓝鲨牙齿" -> "BLUE_SHARK_TOOTH"
                "催化剂" -> "CATALYST"
                "祝福诱饵", "祝福鱼饵", "幸运诱饵", "幸运鱼饵" -> "BLESSED_BAIT"
                "附魔萤石粉" -> "ENCHANTED_GLOWSTONE_DUST"
                "附魔墨囊" -> "ENCHANTED_INK_SACK"
                "附魔仙人掌" -> "ENCHANTED_CACTUS"
                "附魔甘蔗" -> "ENCHANTED_SUGAR_CANE"
                "附魔熟鲑鱼" -> "ENCHANTED_COOKED_SALMON"
                "附魔种子" -> "ENCHANTED_SEEDS"
                "附魔骨块" -> "ENCHANTED_BONE_BLOCK"
                "恶魂之泪" -> "GHAST_TEAR"
                "附魔末影珍珠" -> "ENCHANTED_ENDER_PEARL"
                "unstable龙碎片" -> "UNSTABLE_FRAGMENT"
                "紫糖" -> "PURPLE_CANDY"
                "尖刺鱼饵", "尖刺诱饵" -> "SPIKED_BAIT"
                "附魔发酵蜘蛛眼" -> "ENCHANTED_FERMENTED_SPIDER_EYE"
                "附魔金块" -> "ENCHANTED_GOLD_BLOCK"
                "附魔从林木" -> "ENCHANTED_JUNGLE_LOG"
                "附魔隧石" -> "ENCHANTED_FLINT"
                "铁锭" -> "IRON_INGOT"
                "附魔绿宝石块" -> "ENCHANTED_EMERALD_BLOCK"
                "附魔粘土", "附魔黏土" -> "ENCHANTED_CLAY_BALL"
                "萤石", "萤石粉" -> "GLOWSTONE_DUST"
                "金锭" -> "GOLD_INGOT"
                "僵尸内脏" -> "REVENANT_VISCERA"
                "狼蛛丝", "狼蛛线" -> "TARANTULA_SILK"
                "附魔羊肉" -> "ENCHANTED_MUTTON"
                "附魔铁锭", "附魔铁" -> "ENCHANTED_IRON"
                "sc3000", "sc3k", "压缩机3000", "超级压缩机", "超级压缩机3000", "打包机3000", "超级打包机3000", "超级打包机", "超级打包机3k", "超级压缩机3k", "压缩机3k", "打包机3k" -> "SUPER_COMPACTOR_3000"
                "超级蛋", "超级鸡蛋" -> "SUPER_EGG"
                "股票" -> "STOCK_OF_STONKS"
                "附魔甘草块" -> "ENCHANTED_HAY_BLOCK"
                "附魔骨头" -> "ENCHANTED_BONE"
                "附魔纸" -> "ENCHANTED_PAPER"
                "附魔钻石块" -> "ENCHANTED_DIAMOND_BLOCK"
                "万圣节鱼饵", "万圣节诱饵" -> "SPOOKY_BAIT"
                "超龙碎片", "super龙碎片", "superior龙碎片" -> "SUPERIOR_FRAGMENT"
                "绿宝石" -> "EMERALD"
                "附魔兔子脚" -> "ENCHANTED_RABBIT_FOOT"
                "浅色鱼饵" -> "LIGHT_BAIT"
                "土豆书", "热土豆书" -> "HOT_POTATO_BOOK"
                "附魔冰", "附魔冰块" -> "ENCHANTED_ICE"
                "粘土", "黏土" -> "CLAY_BALL"
                "old龙碎片", "老龙碎片" -> "OLD_FRAGMENT"
                "绿礼物" -> "GREEN_GIFT"
                "浮冰" -> "PACKED_ICE"
                "睡莲", "荷叶" -> "WATER_LILY"
                "仓鼠跑轮" -> "HAMSTER_WHEEL"
                "附魔黑曜石" -> "ENCHANTED_OBSIDIAN"
                "附魔煤炭" -> "ENCHANTED_COAL"
                "煤炭" -> "COAL"
                "附魔石英" -> "ENCHANTED_QUARTZ"
                "附魔煤炭块" -> "ENCHANTED_COAL_BLOCK"
                "末影珍珠" -> "ENDER_PEARL"
                "狼人皮" -> "WEREWOLF_SKIN"
                "附魔海晶沙砾" -> "ENCHANTED_PRISMARINE_CRYSTALS"
                "代达罗斯棍" -> "DAEDALUS_STICK"
                "附魔湿海绵" -> "ENCHANTED_WET_SPONGE"
                "附魔鱼", "附魔生鱼" -> "ENCHANTED_RAW_FISH"
                "末地石" -> "ENDER_STONE"
                "石英" -> "QUARTZ"
                "恶臭腐肉" -> "FOUL_FLESH"
                "生牛肉", "牛肉", "生牛排" -> "RAW_BEEF"
                "附魔末影之眼" -> "ENCHANTED_EYE_OF_ENDER"
                "外质" -> "ECTOPLASM"
                "甘蔗" -> "SUGAR_CANE"
                "岩浆膏", "演讲稿" -> "MAGMA_CREAM"
                "鲨鱼鱼饵", "鲨鱼诱饵", "鲨鱼饵" -> "SHARK_BAIT"
                "红礼物" -> "RED_GIFT"
                "附魔生牛肉", "附魔牛肉", "附魔生牛排" -> "ENCHANTED_RAW_BEEF"
                "附魔羽毛" -> "ENCHANTED_FEATHER"
                "附魔粘液块", "附魔史莱姆块" -> "ENCHANTED_SLIME_BLOCK"
                "附魔橡木" -> "ENCHANTED_OAK_LOG"
                "兔子皮" -> "RABBIT_HIDE"
                "白礼物" -> "WHITE_GIFT"
                "兔子肉", "兔肉", "生兔子肉", "生兔肉" -> "RABBIT"
                "地狱疣" -> "NETHER_STALK"
                "火药" -> "SULPHUR"
                "暗黑诱饵" -> "DARK_BAIT"
                "附魔胡萝卜" -> "ENCHANTED_CARROT"
                "附魔南瓜" -> "ENCHANTED_PUMPKIN"
                "狮鹫羽毛", "格里芬羽毛" -> "GRIFFIN_FEATHER"
                "腐肉" -> "ROTTEN_FLESH"
                "附魔熟鱼" -> "ENCHANTED_COOKED_FISH"
                "黑曜石" -> "OBSIDIAN"
                "小鱼鱼饵", "小鱼饵", "小鱼诱饵" -> "MINNOW_BAIT"
                "附魔岩浆膏" -> "ENCHANTED_MAGMA_CREAM"
                "附魔火箭", "附魔烟花" -> "ENCHANTED_FIREWORK_ROCKET"
                "皮革" -> "LEATHER"
                "附魔熟羊肉", "附魔熟羊排" -> "ENCHANTED_COOKED_MUTTON"
                "附魔生兔肉", "附魔兔肉", "附魔生兔子肉", "附魔兔子肉" -> "ENCHANTED_RABBIT"
                "附魔面包" -> "ENCHANTED_BREAD"
                "烟熏土豆书", "fuming土豆书" -> "FUMING_POTATO_BOOK"
                "附魔木炭" -> "ENCHANTED_CHARCOAL"
                "附魔烈焰粉" -> "ENCHANTED_BLAZE_POWDER"
                "召唤之眼" -> "SUMMONING_EYE"
                "鱼饵", "鱼诱饵" -> "FISH_BAIT"
                "雪块" -> "SNOW_BLOCK"
                "附魔熟土豆", "附魔烤土豆", "附魔熟马铃薯", "附魔烤马铃薯" -> "ENCHANTED_BAKED_POTATO"
                "压缩机" -> "COMPACTOR"
                "附魔钻石" -> "ENCHANTED_DIAMOND"
                "集市曲奇" -> "BAZAAR_COOKIE"
                "秘银", "秘银矿" -> "MITHRIL_ORE"
                "精炼秘银", "精制秘银" -> "REFINED_MITHRIL"
                "钛", "钛矿石" -> "TITANIUM_ORE"
                "附魔钛" -> "ENCHANTED_TITANIUM"
                "精炼钛", "精制钛" -> "REFINED_TITANIUM"
                "流星", "星落" -> "STARFALL"
                "粗糙玉石", "粗糙jade宝石" -> "ROUGH_JADE_GEM"
                "瑕疵玉石", "瑕疵jade宝石" -> "FLAWED_JADE_GEM"
                "良好玉石", "精细玉石", "良好jade宝石" -> "FINE_JADE_GEM"
                "无瑕玉石", "无瑕jade宝石" -> "FLAWLESS_JADE_GEM"
                "完美玉石", "完美jade宝石" -> "PERFECT_JADE_GEM"
                "粗糙琥珀", "粗糙amber宝石" -> "ROUGH_AMBER_GEM"
                "瑕疵琥珀", "瑕疵amber宝石" -> "FLAWED_AMBER_GEM"
                "良好琥珀", "精细琥珀", "良好amber宝石" -> "FINE_AMBER_GEM"
                "无瑕琥珀", "无瑕amber宝石" -> "FLAWLESS_AMBER_GEM"
                "完美琥珀", "完美amber宝石" -> "PERFECT_AMBER_GEM"
                "粗糙黄玉", "粗糙topaz宝石" -> "ROUGH_TOPAZ_GEM"
                "瑕疵黄玉", "瑕疵topaz宝石" -> "FLAWED_TOPAZ_GEM"
                "良好黄玉", "精细黄玉", "良好topaz宝石" -> "FINE_TOPAZ_GEM"
                "无瑕黄玉", "无瑕topaz宝石" -> "FLAWLESS_TOPAZ_GEM"
                "完美黄玉", "完美topaz宝石" -> "PERFECT_TOPAZ_GEM"
                "粗糙蓝宝石", "粗糙sapphire宝石" -> "ROUGH_SAPPHIRE_GEM"
                "瑕疵蓝宝石", "瑕疵sapphire宝石" -> "FLAWED_SAPPHIRE_GEM"
                "良好蓝宝石", "精细蓝宝石", "良好sapphire宝石" -> "FINE_SAPPHIRE_GEM"
                "无瑕蓝宝石", "无瑕sapphire宝石" -> "FLAWLESS_SAPPHIRE_GEM"
                "完美蓝宝石", "完美sapphire宝石" -> "PERFECT_SAPPHIRE_GEM"
                "粗糙紫晶石", "粗糙紫晶", "粗糙amethyst宝石" -> "ROUGH_AMETHYST_GEM"
                "瑕疵紫晶石", "瑕疵紫晶", "瑕疵amethyst宝石" -> "FLAWED_AMETHYST_GEM"
                "良好紫晶石", "精细紫晶", "精细紫晶石", "良好紫晶", "良好amethyst宝石" -> "FINE_AMETHYST_GEM"
                "无瑕紫晶石", "无瑕紫晶", "无瑕amethyst宝石" -> "FLAWLESS_AMETHYST_GEM"
                "完美紫晶石", "完美紫晶", "完美amethyst宝石" -> "PERFECT_AMETHYST_GEM"
                "粗糙碧玉", "粗糙jasper宝石" -> "ROUGH_JASPER_GEM"
                "瑕疵碧玉", "瑕疵jasper宝石" -> "FLAWED_JASPER_GEM"
                "良好碧玉", "精细碧玉", "良好jasper宝石" -> "FINE_JASPER_GEM"
                "无瑕碧玉", "无瑕jasper宝石" -> "FLAWLESS_JASPER_GEM"
                "完美碧玉", "完美jasper宝石" -> "PERFECT_JASPER_GEM"
                "粗糙红宝石", "粗糙ruby宝石" -> "ROUGH_RUBY_GEM"
                "瑕疵红宝石", "瑕疵ruby宝石" -> "FLAWED_RUBY_GEM"
                "良好红宝石", "精细红宝石", "良好ruby宝石" -> "FINE_RUBY_GEM"
                "无瑕红宝石", "无瑕ruby宝石" -> "FLAWLESS_RUBY_GEM"
                "完美红宝石", "完美ruby宝石" -> "PERFECT_RUBY_GEM"
                "硬石头", "硬石" -> "HARD_STONE"
                "附魔硬石头", "附魔硬石" -> "ENCHANTED_HARD_STONE"
                "浓缩石", "浓缩石头" -> "CONCENTRATED_STONE"
                "零球" -> "NULL_SPHERE"
                "空卵" -> "NULL_OVOID"
                "零原子" -> "NULL_ATOM"
                "原soulflow", "生soulflow", "原灵魂流", "生灵魂流", "灵魂生料", "灵魂原料", "灵魂生流", "灵魂原流", "生灵魂料", "原灵魂料" -> "RAW_SOULFLOW"
                "经验瓶", "附魔瓶", "小经验瓶", "小附魔瓶" -> "EXP_BOTTLE"
                "中经验瓶", "中附魔瓶", "大经验瓶", "大附魔瓶" -> "GRAND_EXP_BOTTLE"
                "泰坦瓶", "泰坦经验瓶", "泰坦附魔瓶" -> "TITANIC_EXP_BOTTLE"
                "巨经验瓶", "巨型经验瓶", "巨附魔瓶", "巨型附魔瓶" -> "COLOSSAL_EXP_BOTTLE"
                "绿jerry盒" -> "JERRY_BOX_GREEN"
                "蓝jerry盒" -> "JERRY_BOX_BLUE"
                "紫jerry盒" -> "JERRY_BOX_PURPLE"
                "金jerry盒" -> "JERRY_BOX_GOLDEN"
                else -> item.uppercase()
            }
        }
    }
}